[[redirects]]
from = "/pcconsultingasia.com/logo_96/"
to = "/"
status = 301
force = false
[[redirects]]
from = "/pcconsultingasia.com/logoweddingcelebrantsized/"
to = "/"
status = 301
force = false
[[redirects]]
from = "/pcconsultingasia.com/tn_4/"
to = "/"
status = 301
force = false
[[redirects]]
from = "/pcconsultingasia.com/phuket-local-business-magazine-2019/"
to = "/"
status = 301
force = false
[[redirects]]
from = "/pcconsultingasia.com/400dpilogo/"
to = "/"
status = 301
force = false
[[redirects]]
from = "/pcconsultingasia.com/logo_120-2/"
to = "/"
status = 301
force = false
[[redirects]]
from = "/pcconsultingasia.com/woocommerce-placeholder/"
to = "/"
status = 301
force = false
[[redirects]]
from = "/pcconsultingasia.com/pc-consulting-seo-optimization-main-logo-1/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/tn_5/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/tn_6/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/tn_1/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/komodo/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/pc-consulting-asia-top-logo-2/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/cropped-pc-consulting-asia-top-logo-jpg/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/paul-cunliffe-celebrant-me-225x300/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/pc-consulting-asia-logo-scroll/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/pc-consulting-asia-paul-cunliffe-9/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/testimonial-2/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/affiliate-badge_300x300-blue-hosted-sticker/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/beach-wedding-celebrant-20-blackwhite/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/wedding-celebrant-paul-cunliffe/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/unique-phuket-weddings_0895/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/unique-phuket-weddings_0893/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/unique-phuket-weddings_0886/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/unique-phuket-weddings_0885/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/unique-phuket-weddings_0427/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/unique-phuket-weddings_0888/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/unique-phuket-weddings_0891/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/unique-phuket-weddings_0894/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/unique-phuket-weddings_0896/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/unique-phuket-weddings_0892/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/unique-phuket-weddings_0887/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/unique-phuket-weddings_0889/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/unique-phuket-weddings_0897/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/unique-phuket-weddings_0890/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/pc-consulting-asia-top-logo/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/internet-marketing-strategy/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/cropped-logo_96-1-1-png/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/logoweddingcelebrantsized2/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/cropped-logo_96-1-png/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/cropped-logo_96-3-png/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/cropped-logo_120-jpg/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/cropped-logo_96-2-1-png/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/pc-consulting-asia-dark/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/cropped-logo_120-png/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/logopc-consulting-asia/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/logoweddingcelebrant/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/consultant-logo-1/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/cropped-logo_120-jpg-2/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/las-santos-times/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/testimonial-1/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/testimonial-3/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/consultant-3/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/cropped-logo_96-2-png/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/consultant-1/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/cropped-logo_96-png/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/thai-cooking-phuket/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/consultant-2/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/400dpilogo-2/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/tapdaq-blog-image/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/consultant-logo-2/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/file-png-3/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/consultant-4/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/logo_120-3/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/info-daily/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/smalllogo-2/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/file-png-2/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/pcca-cover/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/logo_96-2/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/logo_96-3/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/file-png/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/logo_96-4/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/smalllogo/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/tn_1-3/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/logo_120/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/file-jpg/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/tn_3-2/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/relax-2/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/tn_2-2/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/tn_3/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/paul/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/tn_1-2/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/tn_2/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/tn_5/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/tn_6/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/tn_1/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/komodo/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/pcca-cover-2/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/400dpilogo-3/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/smalllogo-2/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/file-png-2/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/pcca-cover/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/logo_96-2/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/logo_96-3/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/file-png/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/logo_96-4/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/smalllogo/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/tn_1-3/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/logo_120/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/file-jpg/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/tn_3-2/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/relax-2/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/tn_2-2/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/tn_3/"
to = "/"
status = 301
force = false
[[redirects]]
from = "https://pcconsultingasia.com/paul/"
to = "/"
status = 301
force = false